name: EULACompliantRanks
version: 1.0
main: com.Kento.ECR.Main
description: MobTP
commands:
  ecr:
    description: Main Commands!
    usage: /<command>
    aliases: [eula, eulacompliantranks]
  thank:
    description: Thank Commands!
    usage: /<command>
    aliases: [ty]
permissions:
    ecr.*:
        description: Gives access to all ECR commands
        children:
            ecr.adfree: true
            ecr.addonspicker: true
            ecr.addons.superjump: true
            ecr.addons.changingarmor: true
            ecr.addons.hideplayers: true
            ecr.addons.flight: true
            ecr.addons.firework: true
            ecr.addons.paintball: true
            ecr.main
            ecr.thank